apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resources
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: resources/base/
    repoURL: https://github.com/Svabas22/argocd-aks.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  project: default
  source:
    path: ngnix/
    repoURL: https://github.com/Svabas22/argocd-aks.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
