apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-standard-zrs
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_ZRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
