apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmGlobals:
  chartHome: ./charts
helmCharts:
- name: grafana
  version: 8.8.5
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  includeCRDs: true
  namespace: argocd
  valuesFile: values.yaml